import { z } from "zod";
import { extendZodWithOpenApi } from "@asteasolutions/zod-to-openapi";

extendZodWithOpenApi(z);

const userRoles = [
  "SYSTEM_ADMIN",
  "COLLECTOR",
  "MANAGER",
  "STORE_MANAGER",
  "LABORATORY",
] as const;

// Full User Schema for existing users
export const UserSchema = z
  .object({
    id: z.number().openapi({ example: 1 }),
    FirstName: z.string().openapi({ example: "John" }),
    MiddleName: z.string().optional().openapi({ example: "Doe" }),
    LastName: z.string().openapi({ example: "Smith" }),
    Gender: z.string().openapi({ example: "Male" }),
    email: z.string().openapi({ example: "johndoe@example.com" }),
    role: z.enum(userRoles).openapi({ example: "SYSTEM_ADMIN" }),
    password: z.string().openapi({ example: "securepassword123" }),
    username: z.string().openapi({ example: "johndoe" }),
    refreshToken: z.string().nullable().openapi({ example: null }),
    createdAt: z.date().openapi({ example: "2023-07-15T10:00:00.000Z" }),
    updatedAt: z.date().openapi({ example: "2023-07-16T10:00:00.000Z" }),
  })
  .openapi("User");

// Schema for creating new users (without autogenerated fields)
export const NewUserSchema = z
  .object({
    FirstName: z.string().openapi({ example: "John" }),
    MiddleName: z.string().optional().openapi({ example: "Doe" }),
    LastName: z.string().openapi({ example: "Smith" }),
    Gender: z.string().openapi({ example: "Male" }),
    email: z.string().openapi({ example: "johndoe@example.com" }),
    role: z.enum(userRoles).openapi({ example: "COLLECTOR" }),
    password: z.string().openapi({ example: "securepassword123" }),
    username: z.string().openapi({ example: "johndoe" }),
  })
  .openapi("NewUser");

// Export TypeScript types for further use
export type User = z.infer<typeof UserSchema>;
export type NewUser = z.infer<typeof NewUserSchema>;
